sass/chosen.scss
This addresses #1771, which is now fixable because the Chrome team has 
fixed the erroneous "Consider using dppx" console message.
See also:
https://code.google.com/p/chromium/issues/detail?id=336276
http://css-tricks.com/forums/topic/chrome-console-recommends-dppx-instead-of-dpi-even-if-dppx-is-used/#post-187595
=> Add dppx to Retina media query

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee
This fixes #1816 (and fixes #1887).
Props to @jonsprague0000 for [the fix](https://github.com/harvesthq/chosen/issues/1816#issuecomment-37178481). I'm just creating the PR to finally push it into the codebase.
=> fix that touching an item in the result list will also touch the element underneath it

coffee/lib/abstract-chosen.coffee, coffee/lib/select-parser.coffee
Minor patch to close #1692. The `title` attribute from the original `<option>` and `<optgroup>` are preserved when generating the `<li>` for chosen.
=> Added title attribute to options and optgroups

coffee/lib/abstract-chosen.coffee
I noticed a scripting vulnerability just now in `1.3.0` when rendering results — and upon checking `master`, not only is that one present, but there’s also another when rendering a single select’s selected option. 
Demo of the issue using [chosen@`501568a`](https://github.com/harvesthq/chosen/tree/501568a69376c7df2e8db803006f94ff74bcc9f5) (current master): http://jsfiddle.net/hpv4La79/3/.
Fixes #2132, replaces #2209, #1806. Effectively undoes #1638.
=> Fix code execution vulnerabilities.

coffee/lib/abstract-chosen.coffee
If you changed the selection from code and triggered chosen:updated, the label for the optgroup wouldn't appear with `include_group_label_in_selected`. It only appears when clicked on manually by an user.
=> Fix opt group label not appearing when triggering "chosen:updated" event

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee
Fix a bug where the chosen element immediately closes again after opening it with a touch event, because both the touch and mouse events get triggered the first time.
=> Fix touch event propagation

coffee/lib/abstract-chosen.coffee
This is just a rebase and squash of @k-zelenkov's #1971 which fixes #1595.
Thanks @k-zelenkov!
=> Fix issue with group labels when `group_search:false`

coffee/chosen.jquery.coffee
fixed #1562 this class was being added on the prototype version but not in the jquery one. Now is working as expected.
=> fix #1562 now the behavior is the same as the proto version

bower-publish.sh
If we have checked out a commit instead of a branch name, git is in what’s known as “detached head” state.
This is what Travis does all the time — see [the latest build output](https://travis-ci.org/harvesthq/chosen/builds/56181856).
This means that we were never considered to be on the branch “master”, and therefore were never publishing bower-chosen.
We can tweak the git command we’re calling to support either checked out branch names or detached heads — as long as we’re at the commit for a commit that is the head of master, we’re peachykeen!
=> [Travis] Allow detached head when parsing master ref.

.gitignore, Gruntfile.coffee, package.json, spec/basic.spec.coffee, spec/public/specs.js
Hi Chosen,
as mentioned in #1401 there seems to be some appetite for introducing testing to chosen.
This pull request does exactly that by using the great jasmine spec runner for Grunt. It installs phantomjs through npm and uses that to run the tests. If you're not familiar with phantomjs: it's a headless webkit browser that is as good as a real browser.
The specs themselves are fairly simple so far but I tried to show an example of constructing a chosen element entirely in memory, doing some interactions on it and asserting the expected result.
If you want to run the tests just do a
```
npm install
grunt test
```
If you have any questions, please shoot. I'd love to incorporate your feedback into this PR.
=> Add Grunt-powered Jasmine spec runner and a first spec

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee
Clicking on a disabled chosen element focuses it and shows a highlight border around the element. 
You can view an example here: http://jsfiddle.net/HpACF/
This is caused by tabindex -1 being added to the chosen-single anchor tag.
Any anchor tag without an href attribute cannot be tabbed to or focused into. 
By adding tabindex -1 to the anchor tag, it means that it can not be focused into via tabbing.
My fix removes this tabindex -1 attribute from the anchor tag. 
This means that a disabled chosen select box is no longer focusable when disabled, removing the highlight border when clicking into the chosen element.
=> Fixes focus highlighting on disabled chosen select boxes (Chrome, Windows)

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee
#1701 is kind of a non-issue in my eyes, but the change is simple enough and I actually prefer this to what exists now. After selecting a result, we should always be resetting a field's value the same way. This adds an extra class removal call in the non-multiple version, but it's harmless.
What say you?
Fixes #1701
=> Call show_search_field_default after a result is selected.

bower-publish.sh, package.json
Though Bower itself is unopinionated about whcih version is included, the consensus amongst common libraries is to include the unminified versions of source files. People probably use build systems to minify those files for production (I hope).
Fixes #2298 and #2288
=> Update bower-chosen to use unminified versions

sass/chosen.scss
@tjschuck @pfiller @koenpunt @altras
Fixes https://github.com/harvesthq/chosen/issues/2363
Our linear gradients go from top-to-bottom, and according to the [latest syntax](http://www.w3.org/TR/css3-images/#linear-gradients) we should be using `to bottom`, but since that's the default we don't need to specify that. Having no direction will go `to bottom` anyway.
=> Remove "top" from linear-gradient - it's the wrong syntax

public/index.html, public/index.proto.html, public/options.html
Contrary to what the documentation currently states, the search input is actually hidden if there are fewer **or equal** number of options compared to disable_search_threshold .
See the current code for reference: https://github.com/harvesthq/chosen/blob/9a1a59f15a9a50b38a2aeafc0bb0f95c7ca9348a/coffee/chosen.jquery.coffee#L192
=> Adjust doc to actual code: disable_search_threshold

coffee/lib/abstract-chosen.coffee, public/options.html, spec/jquery/max_shown_results.spec.coffee
To increase performance of selects with very many options, an option was
added that limits the number of results drawn. By default, this is set
to infinity, so it does not impact the previous behavior if not set.
=> Added option max_shown_results

coffee/lib/abstract-chosen.coffee
On top of the existing detections of Android and IOS, detect Windows Phone, IE Mobile, Blackberry and BB10.
As discussed in https://github.com/harvesthq/chosen/issues/1848 and https://github.com/harvesthq/chosen/issues/2439
=> Extend mobile browser detection

sass/chosen.scss
@tjschuck @koenpunt @pfiller Fixes https://github.com/harvesthq/chosen/issues/2451#issuecomment-147406851
These two properties are hacks that were needed for versions of IE before 8. Chosen now currently doesn't even render for versions of IE before 8, so they are no longer needed. This also fixes Invalid Property error, as described in the Issue above.
=> Remove zoom:1 and *display:inline

coffee/chosen.jquery.coffee
If option passed is 'destroy' then only call the #destroy method and terminate.
This fixes the issue where a new chosen instance is created unintentionally.
=> Fixes #2095

coffee/lib/abstract-chosen.coffee
Hello Chosen!
When embedding chosen in a chrome extension, the keyboard shortcut includes the option key. If a chosen instance happens to be focused at the time, releasing the option key opens it, but shouldn't. This patch ignores option keyup events.
I ran the build task after making the change like it says to in `contributing.md`, but it didn't change any git-tracked files that I could tell. Let me know if I need to do something else!
=> Don't open up chosen on option keyup.

public/index.html, public/index.proto.html
@tjschuck 
As @koenpunt pointed out in #2435 ... we should use the correct form of lets.
I haven't opened a Chosen PR in a long time.
=> Let us remove a bad apostrophe!

public/options.html
Just fixed a minor typo in the "options" documentation.
=> Fixed typo on options page.

.travis.yml
Followup on #2527 
This enables docker based builds, and updates Git to the latest stable version, to support sorting based on version instead of alphabetically.
=> install latest git to support version sorting

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Last week GitHub [announced](
https://github.com/blog/2111-issue-and-pull-request-templates) support for templates for Issues and Pull Requests to projects to try and help contributors add the right details at the start of a thread.
Given the large number of issues/PRs Chosen gets, adding some templates may help make things a little more manageable. 
I've put together a proposed ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE, which were mostly based on the existing [contributing.md](https://github.com/harvesthq/chosen/blob/master/contributing.md).
Do you think these will be of value? Do you have any proposed changes to my drafts?
=> Add contributing templates

coffee/lib/abstract-chosen.coffee
**Old**
```js
browser_is_supported: function() {
if (/iP(od|hone)/i.test(window.navigator.userAgent)) {
return false;
}
if (/Android/i.test(window.navigator.userAgent)) {
if (/Mobile/i.test(window.navigator.userAgent)) {
return false;
}
}
if (/IEMobile/i.test(window.navigator.userAgent)) {
return false;
}
if (/Windows Phone/i.test(window.navigator.userAgent)) {
return false;
}
if (/BlackBerry/i.test(window.navigator.userAgent)) {
return false;
}
if (/BB10/i.test(window.navigator.userAgent)) {
return false;
}
if (window.navigator.appName === "Microsoft Internet Explorer") {
return document.documentMode >= 8;
}
return true;
}
```
**New**
```js
browser_is_supported: function() {
if ("Microsoft Internet Explorer" === window.navigator.appName) {
return document.documentMode >= 8;
}
if …
```
=> Update browser support check

package.json
Provide a general description of the code changes in your pull request.
Please double-check that:
See the [Pull Requests section of our Contributing Guidelines](https://github.com/harvesthq/chosen/blob/master/contributing.md#pull-requests) for more details.
If your pull request is in reference to one or more open GitHub issues, please mention them here to keep the conversations linked together.
chosen-sprite.png and chosen-sprite@2x.png missing from npm install
https://github.com/harvesthq/chosen/issues/2641
=> missing png files

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee, public/options.html
hide_results_on_select will default to true, to keep it backwards compatible.
the change is quite trivial, but the demand for it is high, so we might consider adding this?
cc: @pfiller @tjschuck @stof 
fixes #1546
=> add hide_results_on_select option

coffee/lib/abstract-chosen.coffee
| Before | After | 
--- | ---
| ![image](https://cloud.githubusercontent.com/assets/351038/18600023/932a5046-7c5b-11e6-962d-8ee14755ecfb.png) | ![image](https://cloud.githubusercontent.com/assets/351038/18600034/a21abf14-7c5b-11e6-8aa8-58c56f210120.png) |
This makes use of the "word boundary matching", which I also used in #1483 (#1465)
=> update regex for highlighting

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee, public/index.html, public/index.proto.html, public/options.html
@harvesthq/chosen-developers I've pulled in [@koenpunt's branch](#1491) and updated the docs to note deprecation of the classname approach.
=> Right to Left initialization option

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, package.json, public/options.html, spec/jquery/events.spec.coffee, spec/proto/events.spec.coffee
This PR removes the dependency on `simulate`, which is old, unmaintained and incomplete.
Replacing costs about 5 lines of code...
It also adds the `input` event to the prototype version.
Builds on #2697
=> Bye bye simulate

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee
this prevents spaces to be collapsed
fixes #791
=> add white-space: pre for search field scaling

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee
When the results are showing, pressing escape only hides the results, and then prevents bubbling.
Also introduced an extra method to retrieve the search input value, so that the `keydown_checker` can be moved to the abstract class. 
This method can also be used as an additional solution for #2370, e.g.:
```js
$('.chosen').chosen().on('chosen:no_results', function(event, data) {
console.log(data.chosen.get_search_field_value());
});
```
fixes #1256 
fixes #2653
=> prevent bubbling of escape key

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee, spec/jquery/basic.spec.coffee, spec/proto/basic.spec.coffee
=> escape default text

contributing.md
A small edit to the 'grunt' section of the `Contributing` to list the important `grunt test` command.
As an experienced dev, the **only thing** I really need to know when wanting to write a PR is how to run the tests, and that was missing.
=> Contributing: add grunt command for tests [ci-skip]

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee
When the select has focus and an option is removed, restore the focus.
fixes #2429
=> restore focus if chosen was activated

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee
Triggering `chosen:close` didn't had any effect when the mouse was hovering the instance. This fixes that to use `close_field` instead of `input_blur` as the associated action.
fixes #2340
=> always close on chosen:close event

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee
For a less scaring diff, [click here](2721/files?w=1)
fixes #2567
=> prevent activating disabled fields

public/index.html, public/index.proto.html, sass/chosen.scss
I have tested this in the following browsers:
| Windows 7 | macOS Sierra |
--- | ---
Latest Chrome | Latest Chrome
Latest Firefox | Latest Firefox
IE8 | Latest Safari
IE9 | 
There's only 1 issue on iOS, and that's that the cursor is visible, even when clipped:
fixes #1413
fixes #1410
fixes #1686
fixes #2402
fixes #2445
fixes #2185
=> clip results instead of moving them

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee
The fix introduced in #2119 prevented all further touch interaction with Chosen like scrolling or selecting options.
I don't know how that has been in there for so long...
I've now updated that to only `preventDefault` the events when the results are not showing.
fixes #2289
fixes #2443
=> only prevent default on touchevents when results are not showing

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, spec/jquery/basic.spec.coffee, spec/proto/basic.spec.coffee
=> consider disabled fieldset for disabled state

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee, public/docsupport/init.js, public/docsupport/init.proto.js, public/docsupport/style.css, public/index.html, public/index.proto.html, sass/chosen.scss
To make Chosen compatible with restrictive Content-Security-Policy's, I've updated the way we apply inline styles to elements.
The HTML used to build the select is now defined in AbstractChosen.
I also updated the documentation pages with a CSP header as an example.
fixes #2423 
related #2575
=> Content-Security-Policy fixes

coffee/lib/abstract-chosen.coffee
Fixes #1729 simply by sending focus to `.search-field input` when clicking `.chosen-choices`.
At first, I imagined two possible solutions to this issue:
1. Modify the width of `.search-field input` to fill the width of `.chosen-choices` minus the width of any currently selected values.
2. Send focus to `.search-field input` when clicking `.chosen-choices`.
The first option was not selected as it was more complicated and it would fail to address the case of clicking inside the red circled area in the following screenshot:
=> Calling activate_field on choices_click, fixes #1729

coffee/chosen.jquery.coffee
without parens the argument to `hasClass` included the `or ...` clause
fixes #2833
=> fix useless condition

coffee/lib/abstract-chosen.coffee
This is a new PR for @koenpunt's excellent #1465. In his words:
> By making use of word boundary matching (http://www.regular-expressions.info/wordboundaries.html) the split word search is much cleaner (no more actual splitting of strings), and the search results are better.
I want to be very careful about merging this in, but I'm loving what I see so far. With default options set:
<table>
<tr>
<th>Search String</th>
<th>Expected to Match</th>
<th>Old way</th>
<th>New way</th>
</tr>
<tr>
<td>Democratic Republic of</td>
<td>Congo, The Democratic Republic of The</td>
<td>:poop:</td>
<td>:+1:</td>
</tr>
<tr>
<td>of America</td>
<td>United States (of America)</td>
<td>:poop:</td>
<td>:+1:</td>
</tr>
<tr>
<td>Holland</td>
<td>Netherlands/Holland</td> …
=> Use word boundary matching

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee, spec/jquery/searching.spec.coffee, spec/proto/searching.spec.coffee
Don't search escaped HTML text
Before this change, if you tried to search for "&" to match "Stuff & Nonsense", what we would do is html-escape _both_ things and compare the escaped strings.
This works fine in the case where you just type "&". However, if you type "mp", that will match the html entity "&amp;" in the middle of the html-escaped text we're comparing it to. Which is incorrect.
Additionally, we highlight our "matched" result. When we do, we break up the entity so that the resulting HTML looks like:
Stuff &a<em>mp</em>; Nonsense
And you get to see what basically looks like garbage on the screen:
The meat of this PR and this PR description comes from [this commit](https://github.com/harvesthq/chosen/commit/0adf2d5bf275dcbdfd72185959a4782158fe36a5). The subsequent commits are just …
=> Fix html entity in search results

spec/jquery/searching.spec.coffee
`.size()` isn’t a thing anymore (it has been removed from jQuery) — looks like these tests snuck in while #2860 was open.
=> Fix master tests: use .length instead of .size().

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee
This PR affects mutiple-select Chosen when using the `hide_results_on_select: false` option introduced in #2687, and fixes #2809.
When `hide_results_on_select: true` (the default), `show_search_field_default()` is called which clears the search input and the results are hidden (which then are re-rendered when displaying again). Great! 
However, when `hide_results_on_select: false` is set, those are not called — leaving the text in the search input as well as not re-rendering the results list (the cause of #2809). Here‘s a reproduction in the Chosen docs (changed to pass `hide_results_on_select: false`) which makes it a lot easier to follow: 
In the demo above, the input should be cleared (“alan” should no longer be typed in Chosen after selecting the result). …
=> Clear search input value, reset results when using hide_results_on_select option.

coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee, coffee/lib/select-parser.coffee, spec/jquery/searching.spec.coffee, spec/proto/searching.spec.coffee
Surprisingly, I don’t think I found any issues in this repo for this one — but we’re incorrectly escaping group names and the no results message in some cases: 
- Group name is not properly escaped when it contains a highlighted search term.
- The user-entered text is never properly escaped in the no results message.
| Before this PR | After this PR | Status |
|---------------|-------------|--------|
|![image](https://user-images.githubusercontent.com/14930/29944785-c70ffd06-8e6c-11e7-92e3-c2086f14ce88.png)|![image](https://user-images.githubusercontent.com/14930/29944915-267e0116-8e6d-11e7-9b0c-6803353d0281.png)|(no issue)|
|![image](https://user-images.githubusercontent.com/14930/29944801-da73005a-8e6c-11e7-9052-756dfec0b086.png)|![image](https://user-images …
=> Fix escaping in group names, no results message.

coffee/lib/abstract-chosen.coffee, spec/jquery/searching.spec.coffee, spec/proto/searching.spec.coffee
@harvesthq/chosen-developers to fix #2821.
This tweaks the search regular expression for use in non-ASCII languages. The `\w` (word character) and `\b` (word boundary) characters are ASCII-only in JavaScript (even with the unicode flag set), so I attempted a “good enough” solution using `\s` (whitespace characters) to achieve a similar effect. This clearly isn’t the best, but for the test cases I imagined it seemed to work well enough. 
Is there a test case you can think of which this doesn’t work well? If so, I’ll write up a test (or you can) and we can adjust the solution.
<details><summary>I originally attempted to use unicode character ranges to better represent “word characters” — but that quickly got out of hand, resulting in a crazy regular expression which performed quite poorly …
=> Fix Chosen for non-ASCII languages.

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee
@harvesthq/chosen-developers to fix #2480.
This PR adjusts the logic used to calculate the width of the text input when in multi-select mode. 
If Chosen is not visible when initialized (it’s within a hidden container), the calculated width of Chosen’s container is `0`. This means that we’re setting the search input width to an initial value of `-10px`, which is nonsense — resulting in a fallback to it’s default width in CSS (25px). 
This, of course, is adjusted after Chosen is interacted with, since it is now visible and the container width can be correctly calculated. 
Since we don’t know when Chosen becomes visible, I propose we adjust the default width for the search input to be the full calculated width, and ignore the calculated container_width if it results in zero. The text doesn’t …
=> Only trim input_width to container_width when calculable.

coffee/lib/abstract-chosen.coffee, spec/jquery/searching.spec.coffee, spec/proto/searching.spec.coffee
Hot on the tails of the 1.8.1 release (and as a follow-up to #2879), this PR fixes a cross-site scripting vulnerability discovered when applying the 1.8.1 release to Harvest. 
When an optgroup’s label is not highlighted, we’re using the unescaped version of the `label` attribute — but we’re safe when the highlighting is added, since we’re [escaping each HTML fragment](https://github.com/harvesthq/chosen/blob/908b0bfc819ef407532c7bf289959045ea3c0b34/coffee/lib/abstract-chosen.coffee#L203) when building the highlighted string.
Included is a test which asserts HTML tags are not rendered into HTML unescaped in this case.
=> Escape optgroup label when appending to HTML.

public/options.html
Just added a short description of the undocumented `group_search` to the options page.
https://github.com/harvesthq/chosen/issues/2752
=> Add group_search to options page

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee, sass/chosen.scss
@harvesthq/chosen-developers to fix #2816, replaces #2780.
This PR removes the deprecated `clip` property by replacing it with `display: none` and `display: block`, just as @bingxie did in #2780 — however, this PR also moves the search input when using a single-select chosen to fix focus issues.
The core issue is that we were relying on the search input to catch keyboard events (including tabbing to the field), and that for single-select chosen instances, the search input was inside of the results drop that is hidden when you’re tabbing to the field. 
When using `left: -9999px`, the element was still technically visible (although it wasn’t) so it could catch keyboard events. When using `clip: rect(0,0,0,0)`, it was also still technically visible (although it wasn’t). 
For single-select …
=> Remove `clip` property by moving chosen-single’s search input.

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee
@harvesthq/chosen-developers 👋 
Fix #2888
When holding command and selecting an option from a multi-select, the selection area should not scroll back to the top. I'll write some tests and push those shortly!
=> Skip highlight when holding the meta key.

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee, spec/jquery/searching.spec.coffee
@harvesthq/chosen-developers to fix #2888, replaces #2900.
Building on @braddunbar’s #2900, this PR skips highlighting the first result as described in that PR and also does not reset the search input. This ensures we can do searchless multiple select when holding the control/meta key: 
This also ensures we can do multiple select while searching using the control/meta key:
This is similar to the suggestion that @koenpunt mentioned in https://github.com/harvesthq/chosen/pull/2867#issuecomment-324076160:
> … it might be relevant to leave the text in, if someone wants to select multiple options that matched their query. So maybe we should only clear the input when there are no more matching options visible?
This PR doesn’t exactly implement this behavior — it instead leaves the input when …
=> Do not highlight first result or clear search input when holding control/meta key.

sass/chosen.scss
@harvesthq/chosen-developers to fix #2942 originally reported by @taichunmin, a follow-up to #2939 which fixed #2816.
I missed a usage of `clip` — when the search input is hidden due to search being disabled in options or having fewer than `disable_search_threshold` items. 
This usage of `clip` was similar to the others — to hide the search input but allow it to still receive keyboard events. We can use the same approach as #2939 — simply make the search input transparent instead.
=> Remove forgotten usage of css `clip`.

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee, sass/chosen.scss
@harvesthq/chosen-developers as a follow-up to #2939, fixing #2953.
As mentioned in #2939: 
> As an aside, I originally went with two inputs — a new one to catch the focus events when the results drop was closed, and the existing search input — however, it quickly became ridiculous because letters typed into the focus input cause the results drop to filter and show at the same time. This meant that I had to forward events that caused letters to be typed into the focus input over to the search input… and simulating keyboard events is gross.
> 
> Using a single input that moves ended up being significantly easier.
This isn’t my first choice, but IE11 has demonstrated interesting behavior when moving a focused input element in the DOM: 
- If an input is moved in the DOM during the processing …
=> Use two inputs for Chosen’s focus and search.

publish-package.sh
@harvesthq/chosen-developers as follow-up to #2966 (which fixed #2945… almost).
Unfortunately, version 1.8.4 did not include the LICENSE in `chosen-package`. Although NPM automatically includes LICENSE files in packages, I overlooked our custom `publish-package.sh` script run on Travis CI builds of this repo, which has a specific list of files to copy to the folder which will be pushed to `chosen-package` and then published by NPM. 
I believe this is… now… the last thing that needs to be done. Whew!
=> Update publish-package.sh to include LICENSE file.

coffee/chosen.jquery.coffee, coffee/chosen.proto.coffee, coffee/lib/abstract-chosen.coffee, sass/chosen.scss
@harvesthq/chosen-developers /cc @jisraelsen 
This PR reverts #2939 and #2943, which attempted to avoid using the deprecated `clip` property and used `display: none`, at the cost of a second input to capture focus events. 
It didn’t work out too well, and has continued to be a headache as we try to use the latest version in Harvest. I think the best thing to do is admit it was the wrong choice and revert it. Juggling focus and key events isn’t standard across browsers, especially while making DOM modifications.
This PR instead leaves the deprecated `clip` property and additionally introduces the same fix using `clip-path`. The result is that browsers that do not support the new standard `clip-path` will fallback to using the deprecated `clip` property, without requiring any additional …
=> Revert previous clip-deprecation fixes in favor of hybrid clip and clip-path.

coffee/lib/abstract-chosen.coffee, spec/jquery/bugfixes.spec.coffee, spec/proto/bugfixes.spec.coffee
Fixes #2996.
An easy fix, we were simply missing a call to `this.escape_html`. To be honest, I'm surprised this hasn't been a reported issue yet.
As a bonus, there are even tests for red-greening the fix!
Many thanks to @cade for his assistance with figuring out was was going on in the Ancient Technology™ test (read: Prototype JS).
=> Escape the `group_label` when rendering it 

package-travis.yml
@harvesthq/chosen-developers See [this comment](https://github.com/harvesthq/chosen/pull/2998#issuecomment-396400137) and the ~3 following ones.
This token has been broken for a while, so I generated a new one, encrypted it, updated the encrypted version, and added documenting comments about where this all comes from for the future.
=> Update encrypted NPM release token and document it

.travis.yml
@satchmorun and I discovered this while pairing on the automatic build stuff — though `node` was failing in the matrix (which is fine), if it ever _succeeded_, either accidentally or intentionally, it would run the publish script twice — once for each success.
Instead of testing against something we know is going to fail without a goal of fixing it, let's just remove it until we think we're going to make it pass.
/cc @harvesthq/chosen-developers
=> Don't run a matrix against node latest; just the version we support (6)
